-- ============================================
-- V36__replace_with_real_gta_mechanic_shops.sql
-- Replace all demo stores with 100 real GTA mechanic shops
-- ============================================

TRUNCATE TABLE stores CASCADE;

INSERT INTO stores (
    name,
    address,
    city,
    state,
    postal_code,
    country,
    rating,
    rating_count,
    services_text
) VALUES

-- North York / Thornhill

('Assured Automotive','6167 Yonge St','North York','ON','M2M 3X2','Canada',NULL,0,'Auto repair and mechanical services'),
('Toronto Mobile Mechanic Inc.','7171 Yonge St','Thornhill','ON','L3T 0C5','Canada',NULL,0,'Mobile mechanic services'),
('BATHURST CAR CARE','5901 Bathurst St','North York','ON','M2R 1Y7','Canada',NULL,0,'Car repair and maintenance'),
('Abel''s Mobile Mechanic Service','145 Churchill Ave','North York','ON','M2N 1Z3','Canada',NULL,0,'Mobile mechanic services'),
('Blankenship Shop','3 Athabaska Ave','North York','ON','M2M 2T6','Canada',NULL,0,'General auto repair'),
('Paiman Auto Glass','3181 Bayview Ave','North York','ON','M2K 2Y2','Canada',NULL,0,'Auto glass repair'),
('OB''S Mobile Car Tinting','6021 Yonge St','North York','ON','M2M 3W2','Canada',NULL,0,'Car tinting services'),
('DOGO AUTO','93 Finch Ave E','North York','ON','M2N 4R4','Canada',NULL,0,'Auto repair'),
('Rambo Car Care','4841 Yonge St','North York','ON','M2N 5X2','Canada',NULL,0,'Car care and service'),
('Location Tire Mobile Services','33 Sheppard Ave E','North York','ON','M2N 7K1','Canada',NULL,0,'Mobile tire services'),
('Auto Glass Canada North York','5000 Yonge St #1901','North York','ON','M2N 0A7','Canada',NULL,0,'Auto glass services'),
('Crest Windshield Auto Glass','65 Spring Garden Ave','North York','ON','M2N 6H9','Canada',NULL,0,'Windshield repair'),
('Romana Truck Repair Inc Mobile Mechanic','North York','North York','ON','M2N 6K9','Canada',NULL,0,'Truck repair and mobile mechanic'),
('Migo Tire Corp.','88 Grandview Way','North York','ON','M2N 6V6','Canada',NULL,0,'Tire services'),
('Canadian Auto Part Inc','5949 Yonge St','North York','ON','M2M 3V8','Canada',NULL,0,'Auto parts'),
('Levecanada Auto Parts Inc.','12 Ballyconnor Ct','North York','ON','M2M 4C6','Canada',NULL,0,'Auto parts'),
('Beck Automotive Ltd','355 John St.','Thornhill','ON','L3T 5W5','Canada',NULL,0,'Automotive repair'),
('Guardian Auto Centre','274 Steeles Ave E','Thornhill','ON','L3T 1A7','Canada',NULL,0,'Auto service'),
('MR Automotive','83 Glen Cameron Rd','Thornhill','ON','L3T 1N8','Canada',NULL,0,'Auto repair'),
('Eurolize Auto Boutique','85 Glen Cameron Rd','Thornhill','ON','L3T 1N8','Canada',NULL,0,'Auto boutique services'),
('Leo''s Auto Service Centre','134 Doncaster Ave #7','Thornhill','ON','L3T 1L3','Canada',NULL,0,'Auto service'),
('Eli''s Auto Service','33 Glen Cameron Rd','Markham','ON','L3T 1N9','Canada',NULL,0,'Auto service'),
('Utrust Auto Repair','75 Glen Cameron Rd #7','Markham','ON','L3T 1N8','Canada',NULL,0,'Auto repair'),
('Glen Cameron Auto Service Inc','71 Glen Cameron Rd','Thornhill','ON','L3T 1P5','Canada',NULL,0,'Auto service'),
('Auto Trust Technicians','79 Green Ln','Thornhill','ON','L3T 6K6','Canada',NULL,0,'Automotive technicians'),
('ProColor Collision Thornhill','71 Glen Cameron Rd Unit 7','Thornhill','ON','L3T 1P5','Canada',NULL,0,'Collision repair'),
('CARSTAR North Toronto','82 Green Ln Unit #2','Thornhill','ON','L3T 6K9','Canada',NULL,0,'Collision repair'),
('Assured Automotive (Thornhill)','7200 Yonge St','Thornhill','ON','L4J 1V8','Canada',NULL,0,'Auto repair'),
('Four Star Automotive Certigard','7738 Yonge St','Thornhill','ON','L4J 1W2','Canada',NULL,0,'Automotive repair'),
('Motorhead Speed Shop','4610 Dufferin St Unit 16B','North York','ON','M3H 5S4','Canada',NULL,0,'Performance auto services'),
('Glennalan Motors Limited','65 Brisbane Rd','North York','ON','M3J 2K3','Canada',NULL,0,'Auto repair'),
('Pro Auto Body Shop','73 Alness St Unit 1','North York','ON','M3J 2H2','Canada',NULL,0,'Auto body repair'),
('Atlas Auto Body','169 Limestone Crescent','North York','ON','M3J 2R1','Canada',NULL,0,'Auto body repair'),
('Auto Ready – Reliable Auto Care','148 Limestone Crescent','North York','ON','M3J 2Y8','Canada',NULL,0,'Auto care'),
('Leons Auto Body','9 Vanley Crescent','North York','ON','M3J 2B7','Canada',NULL,0,'Auto body'),
('MGM Auto Body Shop','17 Tangiers Rd','North York','ON','M3J 2B1','Canada',NULL,0,'Auto body'),
('Collision Center – Unique Automotive 214','4544 Dufferin St Unit 30-31','North York','ON','M3H 5X2','Canada',NULL,0,'Collision repair'),
('AUTO REPAIR & COLLISION CENTRE','4544 Dufferin St Unit 16','North York','ON','M3H 5X2','Canada',NULL,0,'Repair and collision'),
('Manzel Auto Service','4544 Dufferin St','North York','ON','M3H 5X2','Canada',NULL,0,'Auto service'),
('Cherry Auto Mechanic Shop','4544 Dufferin St Unit 23','North York','ON','M3H 5X2','Canada',NULL,0,'Auto mechanic'),
('Lawson Automotive','4544 Dufferin St Unit 32','North York','ON','M3H 5X2','Canada',NULL,0,'Automotive service'),
('Exodus Auto','4544 Dufferin St Unit 20-21','North York','ON','M3H 5X2','Canada',NULL,0,'Auto repair'),
('Superior Tire & Auto – Downsview','4300 Dufferin St','North York','ON','M3H 5R9','Canada',NULL,0,'Tire and auto service'),
('Star Tire and Service Inc','20 Alness St','North York','ON','M3J 3H4','Canada',NULL,0,'Tire service'),
('Good Tech Auto Centre Inc','1100 Finch Ave W #206-207','North York','ON','M3J 3H4','Canada',NULL,0,'Auto repair'),
('Fix-n-Go – Toronto Auto Repair Service','1100 Finch Ave W Unit 6B','North York','ON','M3J 2E2','Canada',NULL,0,'Auto repair'),
('SMT Automotive','1100 Finch Ave W Unit 3B','North York','ON','M3J 2A2','Canada',NULL,0,'Automotive repair'),
('Z-Auto','1100 Finch Ave W #8','North York','ON','M3J 2T2','Canada',NULL,0,'Auto repair'),
('Best Quality Auto','1100 Finch Ave W Unit 20','North York','ON','M3J 2T2','Canada',NULL,0,'Auto service'),
('Auto Guyz Tire + Automotive','1185 Finch Ave W','North York','ON','M3J 2E8','Canada',NULL,0,'Tire and automotive services'),

-- Etobicoke, Scarborough, Mississauga, Brampton

('Islington Village Automotive','79 Shorncliffe Rd','Etobicoke','ON','M8Z 5K3','Canada',NULL,0,'Auto repair'),
('Simplicity Car Care Etobicoke','87 Shorncliffe Rd','Etobicoke','ON','M8Z 5K3','Canada',NULL,0,'Car care'),
('Technik Auto Service Etobicoke','48 Six Point Rd','Etobicoke','ON','M8Z 2X3','Canada',NULL,0,'Mechanical services'),
('Cochrane Automotive','73 Chauncey Ave','Etobicoke','ON','M8Z 2Z2','Canada',NULL,0,'Auto repair'),
('Superior Automotive','16 Goodrich Rd','Etobicoke','ON','M8Z 2H1','Canada',NULL,0,'Automotive service'),
('Master Mechanic Etobicoke','32 Jutland Rd','Etobicoke','ON','M8Z 2G9','Canada',NULL,0,'Mechanical repair'),
('S Force Auto Repair','66 N Queen St','Etobicoke','ON','M8Z 2C4','Canada',NULL,0,'Auto repair'),
('Alps Auto Repair Inc','14 Drummond St','Etobicoke','ON','M8V 1Y8','Canada',NULL,0,'Auto repair'),
('Nelson''s Certified Auto Repair','226 Royal York Rd','Etobicoke','ON','M8V 2A7','Canada',NULL,0,'Certified repair'),
('High Quality Auto Service','45 Iron St','Etobicoke','ON','M9W 1H1','Canada',NULL,0,'Auto service'),
('Airport Car Repair Centre','11 Belfield Rd','Etobicoke','ON','M9W 1E8','Canada',NULL,0,'Car repair'),
('Active Green+Ross Tire & Automotive','104 Rexdale Blvd','Etobicoke','ON','M9W 1P5','Canada',NULL,0,'Tire and automotive'),
('Rexdale Auto Centre','183 Rexdale Blvd','Etobicoke','ON','M9W 1P7','Canada',NULL,0,'Auto repair'),
('All-Tech Auto Sales & Service','179 Rexdale Blvd','Etobicoke','ON','M9W 1P7','Canada',NULL,0,'Auto sales and service'),
('Rexdale Motors','41 Brydon Dr','Etobicoke','ON','M9W 4N3','Canada',NULL,0,'Auto repair'),
('Radman Radtech Auto Repair','321 Rexdale Blvd','Etobicoke','ON','M9W 1R8','Canada',NULL,0,'Auto repair'),
('Prestige Service Centre','2044 Kipling Ave','Etobicoke','ON','M9W 4J9','Canada',NULL,0,'Auto service'),
('Grace Auto Service Ltd.','32 Stoffel Dr Unit 1','Etobicoke','ON','M9W 1A8','Canada',NULL,0,'Auto service'),
('East Mall Automotive','1057 Martin Grove Rd','Etobicoke','ON','M9W 4W6','Canada',NULL,0,'Automotive repair'),
('Fine Tuned Autos','2441 Weston Rd','York','ON','M9N 2A1','Canada',NULL,0,'Auto repair'),
('Master Autos – Auto Repair & Service Toronto','2300 Finch Ave W Unit #19','North York','ON','M9M 2Y3','Canada',NULL,0,'Auto repair'),
('Fenmar Auto Service','2420 Finch Ave W Unit #14','North York','ON','M9M 2E2','Canada',NULL,0,'Auto service'),
('SUMIN AUTO','2400 Finch Ave W','North York','ON','M9M 2C8','Canada',NULL,0,'Auto repair'),
('Sant Auto Repair & Sale','2420 Finch Ave W Unit #17','North York','ON','M9M 2E2','Canada',NULL,0,'Repair and sales'),
('369 Auto Service','750 Oakdale Rd','North York','ON','M3N 2Z4','Canada',NULL,0,'Auto service'),
('Seven Auto Repairs','750 Oakdale Rd','North York','ON','M3N 1W6','Canada',NULL,0,'Auto repair'),
('Toronto Automotive Repair','125 Oakdale Rd','North York','ON','M3N 1W2','Canada',NULL,0,'Automotive repair'),
('Scarborough Auto Care','4141 Kingston Rd','Scarborough','ON','M1E 2M3','Canada',NULL,0,'Auto care'),
('Auto Tech Express','614 Danforth Rd Unit 5','Scarborough','ON','M1K 1E9','Canada',NULL,0,'Auto repair'),
('CMB Auto Repairs','2500 Lawrence Ave E #10','Scarborough','ON','M1P 4R7','Canada',NULL,0,'Auto repair'),
('The Car Clinic & Hybrid','139 Midwest Rd Unit 3','Scarborough','ON','M1P 3A6','Canada',NULL,0,'Hybrid and auto repair'),
('A1 Auto Mechanic','170 Nantucket Blvd #1','Scarborough','ON','M1P 4R6','Canada',NULL,0,'Auto mechanic'),
('Top Rated Auto Repair','3596 St Clair Ave E','Scarborough','ON','M1K 1M2','Canada',NULL,0,'Auto repair'),
('EuroMechanic – Redline Automotive','4736 Sheppard Ave E Unit 1','Scarborough','ON','M1S 3V6','Canada',NULL,0,'European auto repair'),
('Mike Vales Auto Service Ltd.','1940 Ellesmere Rd #11','Scarborough','ON','M1H 2V7','Canada',NULL,0,'Auto service'),
('Advanced Auto Repair Inc','285 Old Kingston Rd','Scarborough','ON','M1C 1B4','Canada',NULL,0,'Auto repair'),
('Lucas Automotive Services','6456 Kingston Rd','Scarborough','ON','M1C 1P4','Canada',NULL,0,'Automotive service'),
('My Garage Inc. Mississauga','3300 Mavis Rd Unit 2','Mississauga','ON','L5C 1T8','Canada',NULL,0,'Auto repair'),
('Jo Auto Service','3211 Wolfedale Rd Unit 3','Mississauga','ON','L5C 1V8','Canada',NULL,0,'Auto service'),
('TJF Auto Services Inc.','3211 Wolfedale Rd #1','Mississauga','ON','L5C 1V8','Canada',NULL,0,'Auto repair'),
('BHZ Auto','3545 Hawkestone Rd #1','Mississauga','ON','L5C 2V1','Canada',NULL,0,'Auto repair'),
('Best Auto Repair Service Inc','3635 Hawkestone Rd','Mississauga','ON','L5C 2V1','Canada',NULL,0,'Auto repair'),
('Complete Auto Repair Specialist','3545 Hawkestone Rd #7','Mississauga','ON','L5C 2V1','Canada',NULL,0,'Auto repair'),
('Mississauga Auto Repairs Signature Tire','3085 Wolfedale Rd','Mississauga','ON','L5C 1V8','Canada',NULL,0,'Auto repair and tire'),
('HPower Auto Repair','2458 Haines Rd','Mississauga','ON','L4Y 1Y6','Canada',NULL,0,'Auto repair'),
('Launch Auto Service','1075 Queensway E #12A','Mississauga','ON','L4Y 4C8','Canada',NULL,0,'Auto service'),
('Auto Mobile Mechanic','5958 Greensboro Dr','Mississauga','ON','L5M 5Z9','Canada',NULL,0,'Mobile mechanic'),
('Atlas Auto Collision – Brampton','116 Rutherford Rd S','Brampton','ON','L6W 3J5','Canada',NULL,0,'Collision repair'),
('Maple Auto Body & Repairs Centre','255 Rutherford Rd S Unit 110','Brampton','ON','L6W 4N7','Canada',NULL,0,'Auto body repair'),
('Empire Autobody Repair & Painting Inc.','181 Rutherford Rd S #5','Brampton','ON','L6W 3P4','Canada',NULL,0,'Auto body and painting');